# Generated by Django 3.2 on 2021-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveInGoodHands_app', '0003_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
    ]
