# Generated by Django 3.2 on 2021-04-21 21:50

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveInGoodHands_app', '0006_alter_donation_pick_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
